version = "0.24.2"

[[ifaces]]
name = "eth0"
create_dev_type = "no_need_to_create"
zone_type = "wan"
enable_in_boot = true
wifi_mode = "undefined"

[[ifaces]]
name = "eth1"
create_dev_type = "no_need_to_create"
controller_name = "br_lan"
zone_type = "undefined"
enable_in_boot = true
wifi_mode = "undefined"

[[ifaces]]
name = "wlan0"
create_dev_type = "no_need_to_create"
controller_name = "br_lan"
zone_type = "undefined"
enable_in_boot = true
wifi_mode = "undefined"

[[ifaces]]
name = "br_lan"
create_dev_type = "bridge"
zone_type = "lan"
enable_in_boot = true
wifi_mode = "undefined"

[[ipconfigs]]
iface_name = "eth0"
enable = true

[ipconfigs.ip_model]
t = "dhcpclient"
default_router = true
custome_opts = []

[[nats]]
iface_name = "eth0"
enable = false

[nats.nat_config.tcp_range]
start = 32768
end = 65535

[nats.nat_config.udp_range]
start = 32768
end = 65535

[nats.nat_config.icmp_in_range]
start = 32768
end = 65535

[[dhcpv4_services]]
iface_name = "br_lan"
enable = true

[dhcpv4_services.config]
ip_range_start = "192.168.5.100"
server_ip_addr = "192.168.5.1"
network_mask = 24
address_lease_time = 43200
custom_options = []

[[route_lans]]
iface_name = "br_lan"
enable = true

[[route_wans]]
iface_name = "eth0"
enable = true
